# Generated by Django 4.0.3 on 2022-04-19 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_profile_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
    ]
