# Generated by Django 4.0.3 on 2022-05-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tel_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
