# Generated by Django 4.0.3 on 2022-05-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_profile_tel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tel_number',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
