# Generated by Django 4.0.3 on 2022-05-01 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alter_profile_tel_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tel_number',
        ),
    ]
