# Generated by Django 4.0.3 on 2022-05-03 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_profile_email_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='snippet',
        ),
    ]
