# Generated by Django 4.0.3 on 2022-05-04 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_remove_post_snippet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pinterest_url',
            new_name='linkedin_url',
        ),
    ]
