# Generated by Django 4.0.3 on 2022-05-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_rename_pinterest_url_profile_linkedin_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='linkedin_url',
        ),
    ]
