# Generated by Django 4.0.3 on 2022-05-04 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_remove_profile_pinterest_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='linkedin_url',
            new_name='pinterest_url',
        ),
    ]
