# Generated by Django 4.0.3 on 2022-05-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_remove_comment_body_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(),
        ),
    ]
