# Generated by Django 4.0.3 on 2022-03-19 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_profile_facebook_url_profile_instagram_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
    ]
